### ISSUE TITLE
Marked V14 でのアップデートによる破壊的変更で MDのレンダリングが出来ない

### ISSUE THREAD

**Issue by CAT5NEKO** [ikasoba/dejamu#41]
先日あたりからデプロイ時にActionsがエラーを出すのでログを確認したところ、
marked辺りでエラーが発生しているのを見受けました。

![image](https://github.com/user-attachments/assets/2b054a81-da0f-41ed-91d0-25aa9bea1ea1)

importでも定義されているmarked.tsファイルを参照すると、バージョンアップに伴う変更のコミットが確認されたのでリリース情報を見てみると、レンダラーがトークンオブジェクトを受け取る仕組みに変更されたようで、これがデプロイの失敗に影響しているように思えます。

https://github.com/markedjs/marked/releases/tag/v13.0.0

**Comment by ikasoba** [comment]
[0.0.25](https://github.com/ikasoba/dejamu/releases/tag/0.0.25) で修正致しました！報告ありがとうございます！ ![](https://github.com/user-attachments/assets/b78d69c3-d810-4db4-91be-4b0202e137ce)[^1]

最新のバージョンはプロジェクト内の `deno.json` に含まれる dejamu のバージョンを書き換えることで適用できます

[^1]: ﾈｺﾁｬﾝ絵文字 by しかまつ, https://note.com/shikamatsu/n/nd217dc0617db
